apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: zenml-postgres
  namespace: ${zenml_namespace}
spec:
  clusterDef: postgresql
  terminationPolicy: WipeOut
  componentSpecs:
  - name: postgresql
    componentDef: postgresql
    replicas: 1
    serviceAccountName: kb-psa-zenml-postgres
    # This tells KubeBlocks to use the secret we created for the initial user/password.
    # The user 'zenml' will be created with the password from the secret.
    userPasswordSecret:
      name: ${zenml_db_secret_name}
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: civo-volume