apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zenml-server
  namespace: ${monitoring_namespace} # Deploys to the monitoring namespace
  labels:
    release: kube-prometheus-stack # Standard label for the Prometheus operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zenml-server
  namespaceSelector:
    matchNames:
    - ${zenml_namespace}
  endpoints:
  - port: http
    path: /api/v1/health
    interval: 30s