image:
  repository: quay.io/cilium/cilium
  tag: v1.17.5
installCRDs: true
kubeProxyReplacement: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  flowRetention: 1h
  eventQueueSize: "1048576"
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - icmp
    serviceMonitor:
      enabled: false
metrics:
  enabled: true
