apiVersion: v1
kind: Namespace
metadata:
  name: kb-demos
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kb-psa-neo4j-test
  namespace: kb-demos
---
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: neo4j-test
  namespace: kb-demos
spec:
  # Use the Neo4j ComponentDefinition
  terminationPolicy: WipeOut
  componentSpecs:
  - name: neo4j
    componentDef: neo4j-1.0.0
    replicas: 1  # Community edition supports only 1 replica
    serviceAccountName: kb-psa-neo4j-test
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi