apiVersion: v1
kind: Namespace
metadata:
  name: mg-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kb-psa-mg-test
  namespace: mg-test
---
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: mg-test
  namespace: mg-test
spec:
  clusterDef: mongodb
  terminationPolicy: WipeOut
  componentSpecs:
    - name: mongodb
      componentDef: mongodb
      replicas: 3
      serviceAccountName: kb-psa-mg-test
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
